### ISSUE TITLE
Shipping Zones Calculator (Quoter)

### ISSUE THREAD

**Issue by mrbigs** [CaliStyle/trailpack-proxy-cart#5]
We will need to be able to handle different shipping carriers (UPS, Fedex, USPS) with proxy-cart. We also need the ability to have the different shipping speeds (over-night, next day, 2 day, ground) for the shipping carriers in the quoter

**Comment by scott-wyatt** [comment]
Moving to https://github.com/CaliStyle/trailpack-proxy-generics/issues/1
